/// Flutter icons FitFitIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FitFitIcon
///      fonts:
///       - asset: fonts/FitFitIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FitFitIcon {
  FitFitIcon._();

  static const _kFontFam = 'FitFitIcon';
  static const _kFontPkg = null;

  static const IconData add_photo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_inactive = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_indeterminate = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_forever = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropdown = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropup = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyes = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite_outline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_off = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_on = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate_next = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate_previous = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_inactive = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_rotate = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
